// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace LeapDayTinkering.RaspberryPi
{
    public static partial class LeapDayTinkeringAppServiceExtensions
    {
    }
}
